version: '3'
services:
  activemq:
    image: webcenter/activemq
    container_name: activemq
    volumes:
    - data:/data
    - log:/var/log/activemq
    ports:
    - '8161:8161'
    - '61616:61616'
    - '61613:61613'
    environment:
    - ACTIVEMQ_ADMIN_LOGIN=root
    - ACTIVEMQ_ADMIN_PASSWORD=password
volumes:
  data:
  log:
networks:
  default:
    external:
      name: docker-network
