version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    hostname: localhost
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:9780'
        gitlab_rails['gitlab_shell_ssh_port'] = 9722
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
    - etc:/etc/gitlab
    - log:/var/log/gitlab
    - data:/var/opt/gitlab
    ports:
    - '9780:9780'
    - '9722:22'
volumes:
  etc:
  log:
  data:
networks:
  default:
    external:
      name: docker-network
