version: '3'
services:
  tomcat:
    image: tomcat
    container_name: tomcat
    ports:
    - '8000:8000'
    volumes:
    - ./webapps:/usr/local/tomcat/webapps
    - ./server.xml:/usr/local/tomcat/conf/server.xml
networks:
  default:
    external:
      name: docker-network
